### ISSUE TITLE
Parameter options for Bovy method

### ISSUE THREAD

**Issue by andersdot** [tholoien/XDGMM#28]
Awesome work, stoked this wrapper exists :) I would also like to use sklearn to optimize the "w parameter" in the Bovy method

       w - (double, default=0.) covariance regularization parameter
            (of the conjugate prior)

Is it possible to add this to the input parameters available to the wrapper?

**Comment by tholoien** [comment]
Yes this should be fairly straightforward to add. I'm currently at a conference but will push an update next week.

**Comment by drphilmarshall** [comment]
@andersdot Hi Lauren! :-) If this is easy, and you have already hacked it in, you could submit a pull request and we could interact further during the code review?

**Comment by tholoien** [comment]
I have added the w parameter to the XDGMM class so that it can be set by the user and used in scikit-learn optimization. (It will only be used when the fitting method = Bovy.) I did some basic testing and I think it's working, but please let me know if it doesn't seem to be functioning correctly.
