### ISSUE TITLE
Cannot install with pip+git (inconsistent tabs/spaces)

### ISSUE THREAD

**Issue by philastrophist** [tholoien/XDGMM#32]
(py36) C:\Users\user>pip install git+https://github.com/tholoien/XDGMM.git
Collecting git+https://github.com/tholoien/XDGMM.git
  Cloning https://github.com/tholoien/XDGMM.git to c:\users\user\appdata\local\temp\pip-pnxrj5xb-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-pnxrj5xb-build\setup.py", line 2, in <module>
        import xdgmm
      File "C:\Users\user\AppData\Local\Temp\pip-pnxrj5xb-build\xdgmm\__init__.py", line 1, in <module>
        from .xdgmm import *
      File "C:\Users\user\AppData\Local\Temp\pip-pnxrj5xb-build\xdgmm\xdgmm.py", line 88
        self.n_components = n_components
                                       ^
    TabError: inconsistent use of tabs and spaces in indentation

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-pnxrj5xb-build\

**Comment by tholoien** [comment]
Sorry about that---not sure how tabs got in there in the first place, but I've pushed an update with consistent spacing. pip install seems to be working for me, but please try again and let me know if you have any more trouble.

**Comment by tholoien** [comment]
Closing this issue since I believe it is resolved.
