### ISSUE TITLE
Aic function addition

### ISSUE THREAD

**Issue by lostsoul3** [tholoien/XDGMM#43]
Dear XDGMM developers,

I have been using your package for one of project where I need to compare my optimal number of components on basis of Akaike Information criteria (AIC) . I have added a function for AIC estimation as done by scikit-learn and a aic_test function similar to bic_test function for aic calculation over a range of number of component values. Kindly look into the PR #42

**Comment by lostsoul3** [comment]
#42

**Comment by tholoien** [comment]
This PR has been completed and the new function added. Thanks for the additional functionality!
