### ISSUE TITLE
Demo notebook

### ISSUE THREAD

**Issue by drphilmarshall** [tholoien/XDGMM#6]
The more I think about it the more I think we want one of these. We could use the code to set up a "truth" XDGMM that we just use to draw some mock data and add some heteroscedastic noise, and then use an "inference" XDGMM with the same number of components to model the data. We could then demonstrate both conditioning and CV investigation of component number. I find these sorts of notebooks are pretty helpful when developing, too. What do you think?

**Comment by drphilmarshall** [comment]
You can see an example of the kind of thing I mean in the [SLCosmo](https://github.com/DarkEnergyScienceCollaboration/SLCosmo) project, where the demo notebook is a "Round Trip" test - choose hyper-parameter, generate mock data, infer hyper-parameter, check it matches the input. The notebook is [here](https://github.com/DarkEnergyScienceCollaboration/SLCosmo/blob/master/notebooks/RoundTrip.ipynb).

**Comment by tholoien** [comment]
Demo is complete.
