### ISSUE TITLE
Set up unit testing and Travis CI 

### ISSUE THREAD

**Issue by drphilmarshall** [tholoien/XDGMM#7]
Important when building re-useable code. We'll need a requirements.txt file for Travis, and the README should be good enough for hosting the (very brief) installation notes.

**Comment by drphilmarshall** [comment]
The SLCosmo project also shows what you need for Travis and unit testing: https://github.com/DarkEnergyScienceCollaboration/SLCosmo

**Comment by tholoien** [comment]
This is setup
